name    'tylerwalts-jdk_oracle'
version '1.2.1'
source 'https://github.com/tylerwalts/puppet-jdk_oracle'
author 'tylerwalts'
license 'Apache License, Version 2.0'
summary 'Module for automating Oracle JDK download and installation'
description 'Module for automating Oracle JDK download and installation, which does not have a dependency on a human download task, file share or centralized architecture design.  It fetches the installer binary from the target server, for the target server.  This approach assumes that automation is more valuable than bandwidth.'
project_page 'https://github.com/tylerwalts/puppet-jdk_oracle'
