name    'spiette-selinux'
version '0.5.4'
source 'http://github.com/spiette/puppet-selinux'
author 'spiette'
license 'Apache License, Version 2.0'
summary 'This class manages SELinux on RHEL based systems.'
description 'This class manages SELinux on RHEL based systems.'
project_page 'http://github.com/spiette/puppet-selinux'
