require 'yaml'
settings = YAML.load_file 'vagrant.yml'

BOX_NAME   		= 'ubuntu/trusty64'
BOX_URL       = 'https://cloud-images.ubuntu.com/vagrant/trusty/current/trusty-server-cloudimg-amd64-vagrant-disk1.box'
box_ip_address = settings['box']['ip_address']


# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = '2'


Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = BOX_NAME
  config.vm.box_url = BOX_URL
	 
  config.vm.network :private_network, ip: box_ip_address
  config.vm.provider :virtualbox do |vb|
      vb.customize ["modifyvm", :id, "--memory", "2048"]
  end

  config.vm.provision "shell", path: "vagrant/01.java.sh"
  config.vm.provision "shell", path: "vagrant/02.maven.sh"
  config.vm.provision "shell", path: "vagrant/03.zookeeper.sh"
  config.vm.provision "shell", path: "vagrant/04.flume-plugins.sh"
  config.vm.provision "shell", path: "vagrant/05.kafka.sh"
  config.vm.provision "shell", path: "vagrant/06.create-kafka-topic.sh"
  config.vm.provision "shell", path: "vagrant/08.orchestrator-dependencies.sh"
  config.vm.provision "shell", path: "vagrant/09.newsreel-evaluator.sh"


  # SPARK EVALUATOR
  #config.vm.provision "shell", path: "vagrant/10.spark.sh"



end

