# -*- mode: ruby -*-
# vi: set ft=ruby :


#BOX_NAME   		= ENV['BOX_NAME']   		|| 'centos64_i386'
#BOX_URI    		= ENV['BOX_URI']    		|| 'http://developer.nrel.gov/downloads/vagrant-boxes/CentOS-6.4-i386-v20131103.box'
BOX_NAME   	  = 'ubuntu/trusty64'
BOX_URI       = 'https://cloud-images.ubuntu.com/vagrant/trusty/current/trusty-server-cloudimg-amd64-vagrant-disk1.box'



nodes = [
  { "node_id" => 1, "hostname" => 'mahout',   "ip" => '192.168.22.100', "box" => BOX_NAME, "boxurl" => BOX_URI, "ram" => 512, "role" => 'fe'}
]

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = '2'

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

	nodes.each do |node|
		
		config.vm.define node["hostname"] do |node_config|
	    	node_config.vm.box = node["box"]
	    	node_config.vm.box_url = node["boxurl"]
	      	node_config.vm.network :private_network, ip: node["ip"]
	      	node_config.vm.hostname = node["hostname"]
	      				
    		node_config.vm.provider 'virtualbox' do |v, override|
				memory = node["ram"] ? node["ram"] : 512;
				v.customize ['modifyvm', :id,
				             '--name', node["hostname"],
				             '--memory', memory.to_s
				             ]
			end

      		# Provisioning puppet on boxes
		    node_config.vm.provision 'shell', inline: 'apt-get -q -y install puppet'
		            
      		node_config.vm.provision 'puppet' do |puppet|  
				puppet.manifests_path 	= 'puppet/manifests'
				puppet.manifest_file	= 'site.pp'          
				puppet.module_path 		= 'puppet/modules'     
			end                                           
      		
   		end
  	end
  	  	
end
